# Generated by Django 3.1.3 on 2021-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='')),
                ('therapy', models.CharField(max_length=200, verbose_name='Terapia')),
            ],
            options={
                'verbose_name': 'Therapy',
                'verbose_name_plural': 'Therapist',
            },
        ),
    ]
