# Generated by Django 3.1.3 on 2021-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
