# Generated by Django 3.1.3 on 2021-10-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20211012_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='therapy',
            new_name='terapia',
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(verbose_name='Duracion (Tiempo) ')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.therapist')),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
            },
        ),
    ]
