# Generated by Django 3.1.3 on 2021-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211012_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duracion (Tiempo) '),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
