# Generated by Django 3.1.3 on 2021-11-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20211012_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=255, verbose_name='Time')),
                ('comments', models.TextField()),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.therapy')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
