# Generated by Django 3.1.3 on 2021-11-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20211105_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='therapist',
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapist',
            field=models.ManyToManyField(to='MainApp.Therapist'),
        ),
    ]
