# Generated by Django 3.1.3 on 2021-11-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20211113_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='therapist',
        ),
        migrations.AddField(
            model_name='therapy',
            name='therapist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MainApp.therapist'),
            preserve_default=False,
        ),
    ]
