# Generated by Django 3.1.3 on 2021-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20211117_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
