# Generated by Django 3.1.3 on 2021-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20211123_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='terms_confirmed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
