# Generated by Django 3.1.3 on 2021-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_appointment_terms_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='terms_confirmed',
        ),
    ]
