# Generated by Django 3.1.3 on 2021-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_remove_appointment_terms_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='add_time',
            field=models.CharField(choices=[("10' more please", "10' more please"), ("20' more please", "20' more please"), ("30' more please", "30' more please")], default=None, max_length=255, verbose_name='ADD TIME'),
        ),
    ]
