# Generated by Django 3.1.3 on 2021-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_appointment_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='add_time',
            field=models.CharField(blank=True, choices=[("10' more please", "10' more please"), ("20' more please", "20' more please"), ("30' more please", "30' more please")], default=None, max_length=255, null=True, verbose_name='ADD TIME'),
        ),
    ]
