# Generated by Django 3.1.3 on 2021-12-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_auto_20211206_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='add_time',
            new_name='please_add_more_time',
        ),
    ]
