# Generated by Django 3.1.3 on 2021-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20211206_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='please_add_more_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='more_time',
            field=models.CharField(blank=True, choices=[("10' more please", "10' more please"), ("20' more please", "20' more please"), ("30' more please", "30' more please")], default=None, max_length=255, null=True, verbose_name='Please add more time'),
        ),
    ]
