# Generated by Django 3.2 on 2021-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_auto_20211206_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='more_time',
            field=models.CharField(blank=True, choices=[("10' more please", "10' more for $25 DKK"), ("20' more please", "20' more for $50 DKK"), ("30' more please", "30' more for $100 DKK")], default=None, max_length=255, null=True, verbose_name='Please add more time'),
        ),
    ]
