# Generated by Django 3.2.3 on 2021-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='short_description',
            field=models.CharField(blank=True, default='Massage', max_length=150, null=True, verbose_name='Descripcion corta'),
        ),
    ]
