# Generated by Django 3.1.3 on 2022-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_therapy_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default='bodyworkz90@gmail.com'),
        ),
    ]
