# Generated by Django 3.1.3 on 2022-01-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_auto_20220127_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='age',
            field=models.CharField(max_length=255, verbose_name='edad'),
        ),
    ]
