# Generated by Django 3.2.3 on 2022-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_auto_20220127_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=255, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='duration',
            field=models.CharField(default='--', max_length=200, verbose_name='Duracion'),
        ),
    ]
