# Generated by Django 3.2.3 on 2022-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=255, verbose_name='Time')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
