# Generated by Django 3.2.3 on 2022-04-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_time_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_available',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.time_available'),
        ),
    ]
