# Generated by Django 3.1.3 on 2022-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_alter_time_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_available',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
