# Generated by Django 3.1.3 on 2022-04-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_appointment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='----', max_length=255, verbose_name='Your address'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_available',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.time_available', verbose_name='Available time'),
        ),
    ]
